### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by Neytus** [Kentico/cloud-sample-app-android-tv#2]
### Proposed solution

In order to make the app source code more robust, add unit tests to all of the classes in the utils folder.

**Comment by JCruz8482** [comment]
I would like to contribute tests.

**Comment by alejandrocq** [comment]
@Neytus I can take a look and create some tests using JUnit 4 ;)

**Comment by Neytus** [comment]
Hi, that's great! Feel free to contribute. :) 
Do not hesitate to ask me in case you would need help.

**Comment by Simply007** [comment]
Hello @alejandrocq . I've just sent you an invitation to the project. If you accept it, I'll be able to assign the issue to you.

**Comment by alejandrocq** [comment]
Hi @Simply007 , I've just accepted your invitation :)

**Comment by Neytus** [comment]
Fixed by #8
